/* REMOVE OS ESPAÇOS DO INICIO */
SELECT LTRIM('     OLÁ') AS RESULTADO;

/* REMOVE OS ESPAÇOS DO FINAL */
SELECT RTRIM('OLÁ     ') AS RESULTADO;

/* REMOVE OS ESPAÇOS DO INICIO E FINAL */
SELECT TRIM('    OLÁ    ') AS RESULTADO;

/* CONCATENANDO */
SELECT CONCAT('OLÁ', ' ', 'TUDO BEM', '?') AS RESULTADO;

/* DEIXA TUDO EM MAIUSCULO */
SELECT UPPER('olá tudo bem?') AS RESULTADO;

/* DEIXA TUDO EM MINUSCULO */
SELECT LOWER('OLÁ TUDO BEM?') AS RESULTADO;

/* ACHAR UMA STRING DENTRO DE OUTRA STRING */
SELECT SUBSTRING('OLÁ, TUDO BEM?', 6) AS RESULTADO;
SELECT SUBSTRING('OLÁ, TUDO BEM?', 6, 4) AS RESULTADO;

SELECT CONCAT(NOME, ' (', CPF, ') ') AS RESULTADO FROM tabela_de_clientes;

/* Faça uma consulta listando o nome do cliente e o endereço completo (Com rua, bairro, cidade e estado). */

SELECT NOME, CONCAT(ENDERECO_1, ' ', BAIRRO, ' ', CIDADE, ' ', ESTADO) AS COMPLETO
FROM tabela_de_clientes